#!/usr/bin/env bash

. <(functions)

main() {
	apt.install                        \
		build-essential            \
		jq                         \
		libffi-dev                 \
		libssl-dev                 \
		libxml2                    \
		libxml2-dev                \
		lsb-release                \
		zlib1g-dev                 \
		#
}

main "$@"
