#!/usr/bin/env bash

. <(functions)

main() {
	local release id codename

	release=node_17.x
	id=$(os.id)

	case $id in
	ubuntu|pop) codename=impish ;;
	debian)     codename=stable ;;
	*)      panic "Unsupported distribution: $id" ;;
	esac

	available node || apt.add                                    \
		nodejs                                               \
		https://deb.nodesource.com/gpgkey/nodesource.gpg.key \
		https://deb.nodesource.com/"$release"                \
		"$codename"                                          \
		main
	
	apt.install    \
		nodejs \
		#

	npm install -g --silent --no-progress npm@latest
	npm install -g --silent --no-progress yarn@latest
}

main "$@"
