#!/usr/bin/env bash

. <(functions)

main() {
	available node || curl -fsSL https://deb.nodesource.com/setup_17.x | bash -s
	
	apt.install    \
		nodejs \
		#

	npm install -g --silent --no-progress npm@latest
	npm install -g --silent --no-progress yarn@latest
}

main "$@"
