#!/usr/bin/env bash

builtin source "${BASH_SOURCE[0]%/*}"/../../lib/functions.sh
builtin source "${BASH_SOURCE[0]%/*}"/../../lib/classroom.sh

# --- Main

bootstrap() {
	assert.privilege
}

initialize() {
	apt.upgrade
}

shutdown() {
	apt.clean
}

# --- Entry

main() {
	bootstrap

	initialize

	provision base/core

	provision runtime/database
	provision runtime/javascript
	provision runtime/python
	provision runtime/ruby

	provision development/bash
	provision development/c
	provision development/database
	provision development/github
	provision development/javascript
	provision development/python
	provision development/ruby

	provision user/bash
	provision user/direnv
	provision user/mc
	provision user/neofetch
	provision user/neovim
	provision user/self
	provision user/tmux

	shutdown
}

main "$@"
