#!/usr/bin/env bash

builtin source "${BASH_SOURCE[0]%/*}"/../../lib/functions.sh
builtin source "${BASH_SOURCE[0]%/*}"/../../lib/classroom.sh

# --- Main

bootstrap() {
	assert.privilege
}

initialize() {
	apt.fix && apt.upgrade && apt.fix
}

shutdown() {
	apt.clean
}

# --- Entry

main() {
	bootstrap

	initialize

	provision runtime/base
	provision runtime/database
	provision runtime/javascript
	provision runtime/python
	provision runtime/ruby

	provision development/base
	provision development/bash
	provision development/c
	provision development/database
	provision development/github
	provision development/javascript
	provision development/python
	provision development/ruby

	provision terminal/base
	provision terminal/bash
	provision terminal/direnv
	provision terminal/mc
	provision terminal/neofetch
	provision terminal/neovim
	provision terminal/self
	provision terminal/tmux

	shutdown
}

main "$@"
