#!/usr/bin/env bash

. <(functions at ...)

# --- Entry

main() {
	local source=${1?${FUNCNAME[0]}: missing argument}; shift

	lfh.put "$(self.root rubocop etc/default-.yml)" .rubocop.yml

	rubocop "$source"
}

main "$@"
