#!/usr/bin/env bash

. <(functions at ...)

# --- Entry

main() {
	local source=${1?${FUNCNAME[0]}: missing argument}; shift

	rubocop --config "$(self.root rubocop etc/default-.yml)" "$source"
}

main "$@"
