#!/usr/bin/env bash

. <(functions at ...)

# --- Entry

main() {
	local source=${1?${FUNCNAME[0]}: missing argument}; shift

	local config=.rubocop.yml

	[[ -f $config ]] || config=$(self.root rubocop etc/default-.yml)

	rubocop --config "$config" "$source"
}

main "$@"
