#!/usr/bin/env bash

. <(functions)

main() {
	apt.install          \
		clang        \
		clang-format \
		cmake        \
		gcc          \
		libbsd-dev   \
		make         \
		tcc          \
		#
}

main "$@"
