#!/usr/bin/env bash

. <(functions)

main() {
	# TODO: Add to support
	curl -fsSL https://github.com/cocogitto/cocogitto/releases/download/4.0.1/cocogitto-4.0.1-x86_64-unknown-linux-musl.tar.gz |
	tar -xz -C /usr/local/bin
}

main "$@"

